### PR TITLE
Add a tab to show the source code snippet in the execute modal.  Adding API reference.

### PR DESCRIPTION
**Pull request by jithinbp**
+ modified API methods to return source code
+ Added tabbed browsing in the execute modal template
+ modified controller to set the source code content from returned json.
psl_virt_showsource

---
+ Added flasgger dependendency.
+ added yml file for sign up routine.
+ navigate to /apidocs/ to view api documentation . e.g. pslab-stage.herokuapp.com/apidocs/
psl_flasgger

---

psl_virt_apidocs

### CODE REVIEW

**Comment by jithinbp** [comment]
@niranjan94 the build failed because an eslint rule prohibits nested interactives

`error  Do not use <button> inside an element with `role="tabpanel"`  nested-interactive`

Googling isn't turning up any pointers. Why is this prohibited? Does this mean tabs cannot have any interactive matter like buttons, textarea, sliders etc?

**Comment by jithinbp** [comment]
@niranjan94 I've still got nothing on why It's not allowed.
Is there an eslint rule I can override, or should I close this PR and implement the `show-source` feature as a toggle or something (Even that is probably a case of `nested-interactive` ) ?

**Comment by niranjan94** [comment]
Rule reference: 
- https://github.com/rwjblue/ember-template-lint/blob/master/docs/rule/nested-interactive.md

For now, remove `role="tabpanel"`

**Comment by jithinbp** [comment]
@niranjan94 please merge this. I took care of the eslint issue.

I also included the following in this PR:
+ API references for user session methods.
+ Example scripts

**Pull request merged**
