### PR TITLE
Migrated database to postgres. Enabled auto-deploy to Heroku

### PR DESCRIPTION
**Pull request by jithinbp**
## Deployment to heroku
Current status of the app can be tested [on the Heroku app here](https://pslab-stage.herokuapp.com/) .

## Migration to postgresql
Uses sqlalchemy to access postgresql. works fine on my local server as well as on the heroku app.

Merging should automatically deploy to [https://pslab-stage.herokuapp.com/](https://pslab-stage.herokuapp.com/)
It has been set to track changes to fossasia/pslab-remote/master
is that okay?

### CODE REVIEW

**Comment by niranjan94** [comment]
@jithinbp squash all your commits please. Read best practices at http://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/

**Comment by niranjan94** [comment]
And your PR title says _Sqlalchemy migrate_ but your commits have a lot of other things too.

**Comment by jithinbp** [comment]
@niranjan94 sorry. I'm working on a fork. My original PR was from my fork to the same branch in the base repository. I did not notice that it was not squashed and merged.
This PR is to merge fossasia/pslab-remote/sqlalchemy_migrate to fossasia/pslab-remote/master . It is supposed to auto-deploy fossasia/pslab-remote/master to heroku rather than use a branch in my fork.
I have updated the comments and title to this PR as well

I'm still uncomfortable about squashing, and most of my PRs with multiple commits were squashed and merged , following which I would delete the branch and start the next task from a new one. Can this PR be squashed and merged as well? 

thanks

**Comment by niranjan94** [comment]
@jithinbp the PR can be squashed and merged. But, we expect the contributors to do the squashing before the PR is opened. 

Please do learn about squashing. Even now, you can do a squash and force push to this branch. The PR will update itself.

**Comment by jithinbp** [comment]
@niranjan94 I shall do the needful.
However, a force push won't work. Let me clarify . I worked on a branch sqlalchemy_migrate on my fork of this repository, and raised a PR to merge with sqlalchemy_migrate in the base repository. **That PR has been merged already**
This PR is to merge a branch of the base repository into the master. My working branch is no longer in the picture. I could maybe do a force push to the branch on the base repository using admin privileges, but that could completely mess things up, no?
please help with a squash and merge, thank you.

**Comment by niranjan94** [comment]
Also I notice that you have created a branch `sqlalchemy_migrate` on the fossasia repository. Please don't do that. Always create branches only on your fork even if you have write access to the repo.

**Comment by niranjan94** [comment]
And also, @jithinbp I'm not sure why there are two PRs for the same thing ? What is it that you were trying to do ?

**Comment by niranjan94** [comment]
> However, a force push won't work. Let me clarify . I worked on a branch sqlalchemy_migrate on my fork of this repository, and raised a PR to merge with sqlalchemy_migrate in the base repository. 

> This PR is to merge a branch of the base repository into the master

Why the two step process ?

**Comment by jithinbp** [comment]
I am not sure. I thought I had raised a PR to merge my-fork/sqlalchemy to fossasia/master , but I must have selected the wrong branch by mistake.  Therefore I had to raise a second PR to test Heroku. Future PRs will be to Master directly. sorry.

**Pull request merged**
