### PR TITLE
added travis file

### PR DESCRIPTION
**Pull request by jithinbp**
Creating PR to check CI status with new configuration file.

### CODE REVIEW

**Comment by viveksb007** [comment]
@jithinbp python 3.4 is not installed by default in [trusty environment](https://docs.travis-ci.com/user/reference/trusty/#Python-imges). We can try removing  ```dist``` from travis or try with ```python 3.6.1```.

**Comment by jithinbp** [comment]
@viveksb007 It's installed. But on trusty it's 3.4.6 not 3.4.4 which I had assumed. 
excerpt from the build log
```
0.01s
0.53sadding /home/travis/.cache/pip to cache
$ python --version
Python 3.4.6
$ pip --version
```

**Comment by jithinbp** [comment]
@viveksb007 
[tutorial followed](https://colinmurraycs373.wordpress.com/2015/04/15/setting-up-travis-ci-for-a-flask-project-w-postgres-backend-database/)
[link for checking travis syntax](https://lint.travis-ci.org/)
[postgres issue thread for travis / why I specified dist:trusty](https://github.com/travis-ci/travis-ci/issues/4264)

**Comment by jithinbp** [comment]
@viveksb007 Both Python builds have passed now :)

**Comment by viveksb007** [comment]
@jithinbp great :+1: 
I read about trusty, python version given was an example for ```2.x``` and ```3.x```.  I thought that only specific version is available.

**Comment by mariobehling** [comment]
Let's try it out! Thanks.

**Pull request merged**
